global:
  scrape_interval: 60s
remote_write:
  - url: ${GRAFANA_CLOUD_PROMETHEUS_URL}
    basic_auth:
      username: ${GRAFANA_CLOUD_PROMETHEUS_USERNAME}
      password: ${GRAFANA_CLOUD_PROMETHEUS_PASSWORD}
scrape_configs:
  - job_name: express-server
    static_configs:
      - targets: ["localhost:3000"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]